### ISSUE TITLE
interpreting results from duplicate variables

### ISSUE THREAD

**Issue by stephens999** [crbasel/hierinf#1]
I ran the example from 
`test_hierarchy` but exactly duplicating every variable.

I hoped to get three significant sets, each containing two duplicate variables
5 and 505; 20 and 520; 46 and 546

however, i got 6 sets, each containing a single variable, and the same
variables were included twice. Is this expected to you?
(Code and results below)

```
n <- 200
p <- 500
library(MASS)
set.seed(3)
x <- mvrnorm(n, mu = rep(0, p), Sigma = diag(p))
colnames(x) <- paste0("Var", 1:p)
beta <- rep(0, p)
beta[c(5, 20, 46)] <- 1
y <- x %*% beta + rnorm(n)

x = cbind(x,x) # duplicate all the variables (so now 1000 variables)

dendr1 <- cluster_var(x = x)
set.seed(68)
sign.clusters1 <- test_hierarchy(x = x, y = y, dendr = dendr1,
                                 family = "gaussian")

sign.clusters1$res.hierarchy
```

`> sign.clusters1$res.hierarchy`
  block      p.value significant.cluster
1    NA 4.335320e-11               Var20
2    NA 4.335320e-11               Var20
3    NA 1.396529e-14               Var46
4    NA 1.396529e-14               Var46
5    NA 4.392261e-08                Var5
6    NA 4.392261e-08                Var5

**Comment by crbasel** [comment]
Thanks a lot! The problem was that the package does not check if the column names of the matrix `x` are unique which they are not if `x <- cbind(x, x)` is used. This messes up the computations.

I have changed the implementation such that the output is correct and a warning is issued for each group or cluster where the p-value could not be calculated due to colinear variables. I have included your example in the unit tests. The new version of the package (v1.3.1) is available on github and will be available on Bioconductor 3.10 (development version) after the next build. 

```
library(MASS)
B <- 50
n <- 200
p <- 500
set.seed(3)
x <- mvrnorm(n, mu = rep(0, p), Sigma = diag(p))
colnames(x) <- paste0("Var", 1:p)
beta <- rep(0, p)
beta[c(5, 20, 46)] <- 1
y <- x %*% beta + rnorm(n)

x <- cbind(x, x) # duplicate all the variables (so now 1000 variables)
colnames(x)[501:1000] <- paste0("D2_", colnames(x)[501:1000])

dendr1 <- cluster_var(x = x)

set.seed(68)
sign.clusters1 <- test_hierarchy(x = x, y = y, dendr = dendr1,
                                                    family = "gaussian")

# # Warning messages
# attr(sign.clusters1$res.hierarchy, "warningMsgs")
```
The output is:
```
> sign.clusters1
  block p.value   significant.cluster
1 NA    1.301e-10 Var20, D2_Var20    
2 NA    2.140e-14 Var46, D2_Var46    
3 NA    9.118e-09 Var5, D2_Var5  
```
